baseURL = 'https://jayinlab.github.io/'
languageCode = 'ko-kr'
title = 'jayinlab'

[taxonomies]
  tag = 'tags'
  series = 'series'

[permalinks]
  posts = '/:slug/'

[params]
  description = 'jayinlab blog (Hugo)'

[outputs]
  home = ['HTML', 'RSS']

[sitemap]
  changeFreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
